apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:259c0873164849eb7f89df45dba3a2116122635c005a7e7f15cdaaa35f313c65
  name: quay.io/llevy/vote-api
  newName: quay.io/llevy/vote-api
